server:
  port: 8080

spring:
  datasource:
    username: tang
    password: 123456
    url: jdbc:mysql://localhost:3306/scw?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource # 方法一，这两种方法，自定义配置类

# 配置mybatis
#mybatis:
#  config-location: classpath:/mybatis/mybatis-config.xml
#  mapper-locations: classpath:/mybatis/mapper/*.xml
